In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [ ]:
x = 3
print(type(x))
print(x)

y = 2.5
print(type(y))
print(y)

<class 'int'>
3
<class 'float'>
2.5


In [ ]:
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"

4
2
6
9


In [ ]:
 x+= 1
print(x)  
x *= 2
print(x) 

4
8


In [ ]:
 y= 2.5
print(type(y)) 
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


In [ ]:
#BOOLEAN
t = True
f = False
print(type(t)) 
print(t and f) 
print(t or f)  
print(not t)   
print(t != f) 


<class 'bool'>
False
True
False
True


In [ ]:
#STRINGS
hello = 'hello'    
world = "world"    
print(hello)       
print(len(hello))  
hw = hello +  ' ' + world 
print(hw)  
hw12 = '%s %s %d' % (hello, world, 12) 
print(hw12)  

hello
5
hello world
hello world 12


In [ ]:
#LISTS
xs = [3, 1, 2]    
print(xs, xs[2]) 
print(xs[-1])     
xs[2] = 'foo'     
print(xs)         
xs.append('bar')
print(xs)        
x = xs.pop()      
print(x, xs) 

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [ ]:
#SLISING
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [ ]:
#LOOPS
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares) 

[0, 1, 4, 9, 16]


In [ ]:
#Dictionaries
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A

cute
True
wet
N/A
wet
N/A


In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [ ]:
#Sets
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


In [ ]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


In [ ]:
#Tuples
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


In [ ]:
#Functions
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [ ]:
#Classes
class Greeter(object):
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable
    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)
g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True) 

Hello, Fred
HELLO, FRED!


In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)    

int64
float64
int64


In [ ]:
#Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
#Questions
#Q1: Write the code to determine the parity of a given number
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

Enter a number:  2


Even number


In [ ]:
#Q2: For a given list of strings, check if the length of the string is even or odd. Print "even" or "odd" accordingly
strings = ["apple", "banana", "kiwi", "grape"]

for s in strings:
    if len(s) % 2 == 0:
        print(s, " even")
    else:
        print(s, " odd")

apple  odd
banana  even
kiwi  even
grape  odd


In [ ]:
#Q3: Write a code to reverse the string "hello" using indexing.
s = "hello"

reversed_s = s[4] + s[3] + s[2] + s[1] + s[0]

print(reversed_s)

olleh


In [ ]:
#Q4: For numbers in range 0 to 100, return a list of those that are multiple of 2 but not 5 using list comprehension 
numbers = [x for x in range(101) if x % 2 == 0 and x % 5 != 0]

print(numbers)

[2, 4, 6, 8, 12, 14, 16, 18, 22, 24, 26, 28, 32, 34, 36, 38, 42, 44, 46, 48, 52, 54, 56, 58, 62, 64, 66, 68, 72, 74, 76, 78, 82, 84, 86, 88, 92, 94, 96, 98]


In [ ]:
#Q5: Generate two numpy arrays x and y of 20 random integers between [1,10], compute a new array where each element is the square of sum of corresponding entries in x and y. Use broadcasting in this question.
import numpy as np

# Step 1: Generate arrays
x = np.random.randint(1, 11, 20)
y = np.random.randint(1, 11, 20)

# Step 2: Compute (x + y)^2 using broadcasting
result = (x + y) ** 2

# Step 3: Print
print("x:", x)
print("y:", y)
print("Result:", result)

x: [ 6  7  3  6  4  4  3  3 10  6  6  3  8  4  2  2  3  2 10  6]
y: [ 2  7  7  3  8  3  8  4  7 10 10  6  7 10  4  3  5  1  8  5]
Result: [ 64 196 100  81 144  49 121  49 289 256 256  81 225 196  36  25  64   9
 324 121]


In [ ]:
#Q6: Given two dictionaries of ids and Mathematics scores, write a function to return a dictionary where keys are students ids and values are a list containing the corresponding student's name and their score
# Step 1: Define dictionaries
names = {
    1: "Ali",
    2: "Sara",
    3: "John"
}

scores = {
    1: 85,
    2: 90,
    3: 78
}

# Step 2: Function
def combine_data(names, scores):
    result = {}

    for key in names:
        result[key] = [names[key], scores[key]]

    return result

# Step 3: Call function
output = combine_data(names, scores)

print(output)

{1: ['Ali', 85], 2: ['Sara', 90], 3: ['John', 78]}


In [ ]:
#Q7: Given a numpy array x, write a function to find all negative elements and replace them with their squares. Use boolean indexing.
import numpy as np

def replace_negatives(x):
    x[x < 0] = x[x < 0] ** 2
    return x

# Example
x = np.array([2, -3, 4, -1, 5])

result = replace_negatives(x)
print(result)

[2 9 4 1 5]


In [ ]:
#Q8: Write a function which takes that numpy 1-D array as input and returns the following:
#1. Maximum value in the array
#2. Standard Deviation
#3. Sum of all the elements in the array
import numpy as np

def array_stats(x):
    max_val = np.max(x)
    std_val = np.std(x)
    sum_val = np.sum(x)
    
    return max_val, std_val, sum_val

# Example
x = np.array([2, 4, 6, 8, 10])

result = array_stats(x)

print("Max:", result[0])
print("Standard Deviation:", result[1])
print("Sum:", result[2])

Max: 10
Standard Deviation: 2.8284271247461903
Sum: 30


In [ ]:
#Q9: Write a Python function that accepts a string and calculates the number of upper case letters and lower case letters.
def count_case(s):
    upper = 0
    lower = 0

    for ch in s:
        if ch.isupper():
            upper += 1
        elif ch.islower():
            lower += 1

    return upper, lower


# Example
text = "Hello World"

result = count_case(text)

print("Uppercase letters:", result[0])
print("Lowercase letters:", result[1])


Uppercase letters: 2
Lowercase letters: 8


In [ ]:
#Q10: Write a function that prints the integers from 1 to 100. But for multiples of three, print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print
"FizzBuzz"
def fizzbuzz():
    for i in range(1, 101):
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)

# Call function
fizzbuzz()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [ ]:
#Q11: Write a function, calculateSum(l,k) which will take a list, l and a number k as input and return two numbers from l that add up to k.
def calculateSum(l, k):
    for i in range(len(l)):
        for j in range(i + 1, len(l)):
            if l[i] + l[j] == k:
                return l[i], l[j]

    return None  # if no pair found


# Example
nums = [2, 7, 11, 15]
k = 9

result = calculateSum(nums, k)
print(result)

(2, 7)


In [ ]:
def find_students(address, students):
    names = []
    for name, details in students.items():
        if details["address"] == address:
            names.append(name)
    return names

students = {
    "Ali": {"age": 6, "address": "Lahore"},
    "Ahmad": {"age": 15, "address": "Islamabad"},
    "Eesha": {"age": 21, "address": "Karachi"},
}

print(find_students("Lahore", students))

In [ ]:
['Ali']

In [ ]:
class evenNumbers:
    def __init__(self, n):
        self.n = n
        self.current = 2   # first positive even number

    def __iter__(self):
        return self

    def __next__(self):   # Python 3 uses __next__
        if self.current <= self.n:
            num = self.current
            self.current += 2
            return num
        else:
            raise StopIteration

myrange = evenNumbers(10)

print(next(myrange))  # 2
print(next(myrange))  # 4


In [ ]:

2
4

In [ ]:
# 1
d = {'simple_key':'hello'}
print(d['simple_key'])

# 2
d = {'k1':{'k2':'hello'}}
print(d['k1']['k2'])

# 3
d = {'k1':[{'nest_key':['this is deep',['hello']]}]}
print(d['k1'][0]['nest_key'][1][0])


hello
hello
hello

In [ ]:

        return result

    # 4. Division
    def Division(self):
        result = self.tup[0]
        for i in self.tup[1:]:
            if i == 0:
                return "Error: Division by zero"
            result /= i
        return result

    # 5. Power
    def Power(self):
        result = self.tup[0]
        for i in self.tup[1:]:
            result **= i
        return result


# Example usage
obj = TupleOperations((2, 3, 2))

print("Tuple:", obj.get_tuple())
print("Addition:", obj.Addition())
print("Subtraction:", obj.Subtraction())
print("Multiplication:", obj.Multiplication())
print("Division:", obj.Division())
print("Power:", obj.Power())

In [ ]:
Tuple: (2, 3, 2)
Addition: 7
Subtraction: -3
Multiplication: 12
Division: 0.3333333333333333
Power: 64

In [ ]:
import re

# Example tweets (you can replace this with input or file data)
tweets = [
    "Hello @ali how are you?",
    "Great work @sara and @ali!",
    "Good morning @ahmed",
    "Thanks @sara for help"
]

# Set to store unique twitter handles
handles = set()

# Extract @handles using regex
for tweet in tweets:
    found = re.findall(r'@\w+', tweet)
    handles.update(found)

# Display result
print("Twitter Handles:")
print(handles)

In [ ]:
Twitter Handles:
{'@sara', '@ali', '@ahmed'}

In [ ]:

import re

articles = [
    "Hello! This is article 1. یہ ایک مثال ہے۔",
    "AI @2026 is growing fast؛ amazing!",
    "Data 123 science - future of AI؟"
]

cleaned_articles = []

for article in articles:
    # 1. Remove punctuation (English + Urdu/Arabic)
    article = re.sub(r"[۔؟٫،؛٪/!@()°.\-;″′]", " ", article)

    # 2. Remove digits
    article = re.sub(r"\d+", " ", article)

    # 3. Remove single English characters (standalone letters)
    article = re.sub(r"\b[a-zA-Z]\b", " ", article)

    # 4. Remove extra spaces
    article = re.sub(r"\s+", " ", article).strip()

    cleaned_articles.append(article)

print("Cleaned Articles:")
print(cleaned_articles)

In [ ]:
['Hello This is article یہ ایک مثال ہے', 
 'AI is growing fast amazing', 
 'Data science future of AI']

In [ ]:
import re

text = "AI in 2026 is amazing! Data 123 grows fast. یہ ایک مثال ہے."

# Urdu digits mapping
urdu_digits = {
    '0': '۰',
    '1': '۱',
    '2': '۲',
    '3': '۳',
    '4': '۴',
    '5': '۵',
    '6': '۶',
    '7': '۷',
    '8': '۸',
    '9': '۹'
}

# Step 1: Replace digits with Urdu digits
for eng, urdu in urdu_digits.items():
    text = text.replace(eng, urdu)

# Step 2: Remove English words
text = re.sub(r'\b[a-zA-Z]+\b', ' ', text)

# Step 3: Remove punctuation marks (English + Urdu set)
text = re.sub(r"[۔؟٫،؛٪/!@()°.\-;″′]", " ", text)

# Step 4: Clean extra spaces
text = re.sub(r'\s+', ' ', text).strip()

print("Cleaned Text:")
print(text)

۲ ۰ ۲ ۶   ۱ ۲ ۳   یہ ایک مثال ہے

In [ ]:
from collections import Counter
import re

articles = [
    "میں نے موبائل استعمال کیا",
    "موبائل بہت مفید ہے",
    "مجھے معلومات حاصل کرنا پسند ہے",
    "موبائل اور میسجنگ اہم ہیں",
    "معلومات کا ذریعہ موبائل ہے"
]

words_list = []

for article in articles:
    # Remove punctuation (basic cleaning)
    article = re.sub(r"[۔؟٫،؛٪/!@()°.\-;″′]", " ", article)

    # Split into words
    words = article.split()

    # Collect words starting with "م"
    for word in words:
        if word.startswith("م"):
            words_list.append(word)

# Count frequency
word_counts = Counter(words_list)

# Top 10 most common
top_10 = word_counts.most_common(10)

print("Top 10 words starting with 'م':")
print(top_10)

In [ ]:
[('موبائل', 3), ('معلومات', 2), ('مجھے', 1), ('میں', 1), ('مفید', 1), ('میسجنگ', 1)]